#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

prog_name="${0##*/}"

function die {
    echo "$prog_name: error: $@"
    exit 1
}

function wfl_assert_on_branch {
    local branch="$1"

    if [[ "$(git rev-parse HEAD)" != "$1" ]]; then
        die "HEAD is not on branch '$1'"
    fi
}

function wfl_get_last_stable_version {
    read -r -d '.' -u <(
            git tag |
            sed -nr 's/^v([[:digit:]]+\.[[:digit:]]+\.0)$/\1/p' |
            sort -V |
            tail -1
        ) \
    wfl_last_stable_version_major \
    wfl_last_stable_version_minor \
    wfl_last_stable_version_patch
}

function wfl_get_last_rc_version {
    read -r -d '.' -u <(
            git tag |
            sed -nr 's/^v([[:digit:]]+\.[[:digit:]]+\.0-rc)$/\1/p' |
            sort -V |
            tail -1
        ) \
    wfl_last_rc_version_major \
    wfl_last_rc_version_minor \
    wfl_last_rc_version_patch
}

function cmd_release-rc {
    local last_major_version=
    local last_rc_version=

    wfl_assert_on_branch master

    last_major_version=$(wfl_get_last_major_version)
    last_rc_version=$(wfl_get_last_rc_version)

    git checkout master
    git tag -s v${wfl_major}.${wfl_minor}.0-rc${wfl_rc}
}

"$@"
